name: CI

on: [push]

jobs:
  sast_scan:
    name: Run Bandit Scam
    runs-on: ubuntu-latest


    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Set up python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.8

    - name: Install bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r . -f json -o bandit-report.json

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with: 
        name: bandit-findings
        path: bandit-report.json
        
